version: '3.3'

services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: forex_buddy
    ports:
      - "5432:5432"